apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: tax-calculator-pipeline
spec:
  workspaces:
    - name: shared-workspace
  params:
    - name: repo-url
      type: string
    - name: branch-name
      type: string
  tasks:
    - name: npminstall
      taskRef:
        name: npm
      workspaces:
        - name: source
          workspace: shared-workspace
    - name: tests
      taskRef:
        name: jasmine
      runAfter:
        - npminstall
      workspaces:
        - name: source
          workspace: shared-workspace
    - name: build
      taskRef:
        name: buildah
        kind: ClusterTask
      runAfter:
        - tests
      workspaces:
        - name: source
          workspace: shared-workspace
      params:
        - name: IMAGE
          value: us.icr.io/sn-labs-dhale/tax-calculator:v1
